### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by OrAsaf**
I've added a docker file that will allow users to build a docker container, as well as adding instructions in the Readme file of how to do it.
I tried it myself, and use it to use the lab and test GraphQL and thought it might be a good contribution.
Let me know if anything needs changing,
Thank you.

### CODE REVIEW

**Comment by righettod** [comment]
Hi,
Thank you very much for this PR and the Docker file, it is a very good idea 😃 
Thanks again
++

**Comment by righettod** [comment]
I have added a GH action in order to build and publish the image on DockerHub every day at 08:00 AM (scheduled build bypass the new DockerHub image removal policy).

**Comment by OrAsaf** [comment]
That's a great idea adding the image to DockerHub using actions.
Thank you for publishing the app, I'll put it to good use 👍

**Comment by righettod** [comment]
Thanks to you for your PR 👍

**Pull request merged**
